## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild Artemis_Mono/Artemis_Mono.sln
  - nunit-console Artemis_Mono/bin/Debug/ArtemisMonoUnitTests.dll
  

